### PR TITLE
ComboMeter/Sensor device. Multiinstance parsing fixes for energy reports.

### PR DESCRIPTION
**Pull request by hybridview**
It took me more time dealing with GITHUB than coding these changes (merging upstream forks, etc). All these changes have been thoroughly tested locally and work great.

Fixed multi-instance report message parsing that caused some report to result in incorrect "Binary" and "Generic" param types. Added new "Combo" device handler to support devices (like HEM) that support both Sensor and Meter. Changed Meter command class to be parsed as "BasicReport" since it is not really a multi-instance (See comments in code for more details). Added Aeon Labs HEM product handler as confirmation for the new combo device handling.

### CODE REVIEW

**Comment by hybridview** [comment]
Hold on... Something isn't right. GIT is killing me. I'm going to destroy my branches and manually merge my changes into a new one. What a pain...

**Comment by hybridview** [comment]
I just created a new branch from your latest commit Gene. I see the same issue as I saw minutes ago, where a new file "ParameterEvent.cs" is not referenced in the ZWavLib project file. Did the commit work from your end? Since my original pull seems to be good, I'm re-opening.

**Comment by genielabs** [comment]
there was a blackout and couldn't fix the error in my last commit. now it should be fixed.

**Comment by hybridview** [comment]
I really hope this pull is all set now. GIT is making me pull my hair out. When I tried to merge your changes into my dev branch (which usually works perfect), it could not add that new ParamEvent file. A search online has other users reporting this issue. I added it myself, but it's now saying I am adding this new file as part of my commit. I don't think this should affect the pull.. :/

**Comment by genielabs** [comment]
I think something is wrong with the pull requests. it result in 29 files changed =/
Can you make some cleanup so that only changes are effectively passed into this? How many files did you change?

**Comment by hybridview** [comment]
I had to do 3 upstream merges from your changes, so much of those 27 files are your changes merged and re-committed. I'm going to delete all my branches and manually add my changes to your latest commit to keep the history clean. Do you plan on making any big commits / rafactorings for MIG and ZWaveLib today? If so, I will wait until tomorrow.

**Comment by genielabs** [comment]
Yes I think it's better waiting until tomorrow as I have another commit pending. No big changes, but it's better keep synchronized when working on same files.

**Comment by hybridview** [comment]
Sounds perfect! Got caught up in family stuff today anyways.

**Pull request closed without merging**
