### PR TITLE
Lookat of some generic widgets : Sensor, Switch and Light

### PR DESCRIPTION
**Pull request by dmayard**
I propose you to make some little changes that don't affect the integrity only permit to add good look of HG UI :
1 - Add indicators imag for Sensor in accordance with my.css and sensor.json
Concerning Sensor.Alarm, Sensor.Generic and Sensor.Level instead of text in the widgets
2 -In switch.json and light.json If the customize DisplayIcon contains '_off' in actif state it's replace by '_on' which permit to have 'on' 'off' different DisplayIcon as generic.

If you agree
Thank's Gene
Dani

### CODE REVIEW

**Comment by genielabs** [comment]
Hi Dani,

some lines do not respect indentations. Also we cannot just replace light/switch widget icon path with _off/_on suffix, because not all icons have the on/off state image file (only the default ones have). Infact if you click on the icon image from the module properties popup, you can pick a different image. None of that non-default images have the corresponding off icon.

**Comment by dmayard** [comment]
Hi Gene,
I know that we can choice an other icon by clicking on thé défaut one. But m'y purpose is that if we choice an other one, with the replace function in case of 'on' state if the imag name doesn't contain '_off'' the replacement is not made, and the same icon will be displayed fort the two states as actually.
I will made the correct Indentation tomorrow.
Cheers

**Comment by genielabs** [comment]
all right, this is ok. thanks!

**Comment by dmayard** [comment]
Hi Gene,

1 - I had the 6 png files in the common.project.
2 - I had one default color in jquery.knob.js 'bluered' for thermostat with one grren zone for eco mode.
3 - I make corrections in the name of black png files
4 - I don't know how to correct the indentation in the json files, because sometimes in the src we find Tab or space.
Cheers

**Comment by genielabs** [comment]
@dmayard I noticed too that html files are not fixed at all regarding indentation. I will take care of that  and fix 'em all later.

**Pull request merged**
