### PR TITLE
Small fixes and improvements to new Scheduler + Auto-restart failed programs feature.

### PR DESCRIPTION
**Pull request by Bounz**

### CODE REVIEW

**Comment by genielabs** [comment]
wow... I see you did some refactoring too. I am not sure how long it will take to review these PRs.
The HG UI library is being rewritten as a stand-alone library and next HG release will probably break compatibility with current widget/ui system, so better not to touch the HTML part any further till then.

**Comment by Bounz** [comment]
Well, my own to changes to UI are not significant, most of the UI changes I have merged from @raptorjr.
Are you going to use your new Zuix framework while rewriting UI part of HG? Are you going to completely decouple frontend part from backend so they will be two separated projects? Do you have some work in progress that I can take a look on?

**Comment by genielabs** [comment]
yes to all questions. :) I'm still working on zuix, so the only progress is that. It will take some week more before I can start to work on hg ui.

**Comment by genielabs** [comment]
Hey Bounz, please move this request to the "1.2-wip" branch so I can merge and test as well.
There's only a little change in the 1.2 branch that is about the location where the pepper1 db is downloaded. It will be downloaded from the new HG site (that I am working on and that will be under 
http://genielabs.github.io/HomeGenie/_hg_files/...

**Comment by Bounz** [comment]
Hi, @genielabs.
I changed the PR as you requested. Looks like it could be merged without conflicts.

**Comment by genemars** [comment]
hey @Bounz it's been long time since this merge. Are you running this version somewhere? Have you had any chance to test it? Is it stable?
Since I decided to postpone the work on the new UI, I'd like to proceed creating a new release (v1.1.526) from this branch anyway.
Btw the location for the pepper db is now here:
https://github.com/genielabs/HomeGenie/tree/gh-pages/_hg_files/zwave

**Comment by Bounz** [comment]
Hi, @genemars.
Yes, I use it in my HG installation since February. Everything works)
As far as I know, some other guys from the forum are also using it. So I think it's safe enough to use it.

I'll change the URL of pepper1db in the MIG project.

**Pull request merged**
