### PR TITLE
Issue statistics correction : At the first entry HG.WebApp.Statistics…

### PR DESCRIPTION
**Pull request by dmayard**
….Refresh is called 5 times due to initialisation of Date fields

Hi Gene, the only way I found to care that issue is to create a variable that is decremented by the 2 first calls of :
    $('#page_analyze_datefrom').on('change', function(){
    $('#page_analyze_dateto').on('change', function(){

### CODE REVIEW

**Comment by dmayard** [comment]
Hi Gene I have added Multiple Statistiques. Mean that It shows every Sensor in the same graph independently.

**Comment by genielabs** [comment]
hey @dmayard what do you think of renaming "Multiple" to "Detail", or something else more easy to understand.

**Comment by genielabs** [comment]
@dmayard I've also noticed an issue. If I change the graph type to "bars" or "splines", it will still show as "lines".

**Comment by dmayard** [comment]
Ok Gene, You are right, we can use Detail instead of Multiple.

**Comment by dmayard** [comment]
As for your graph by hours, "Today detail" remains always as lines. I 
think is not in use for a detail to use "bars", perhaps can autorise 
"splines".

**Pull request merged**
