### PR TITLE
Add Combined Statistics Temperature-Humidity in the same graph for Double Sensors.  Change Multiple by Detail

### PR DESCRIPTION
**Pull request by dmayard**
Hi Gene, look that forum topic :
http://www.homegenie.it/forum/index.php?topic=129.msg6521#msg6521 for see a screnshot.

Cheers
Dani

### CODE REVIEW

**Comment by genielabs** [comment]
Hi dani, I think you should start a new branch "stats" and work there. Anyway this needs more thinking as too much custom code is being added to the statistics class. This is not good. Always prefer generic solutions. For example instead of "stats double" with fixed parameters why not just calling the existing method twice for each field name and so do all the job from the javascript side. this way the user could add more than just two fields, and pick them from a checkbox options list.

**Comment by dmayard** [comment]
Hi Gene,

I agree with you. But I am a little newbye with javascript. It's 
possible to include 2 nested calls to the web :
$.ajax({
     url: '/' + HG.WebApp.Data.ServiceKey + 
'/' + HG.WebApp.Data.ServiceDomain + '/Statistics/Parameter.StatsHours' ....
      type: 'GET',
      success: function (data) {
var stats = eval(data);
$.ajax({
          url: '/' + HG.WebApp.Data.ServiceKey + 
'/' + HG.WebApp.Data.ServiceDomain + '/Statistics/Parameter.StatsHours' ....
            type: 'GET',
            success: function (data) {
var stats1 = eval(data);
               ...
               ...
         });
});

Isn't it ?

**Comment by genielabs** [comment]
just make a function of this and call it twice

**Comment by dmayard** [comment]
Hi Gene,
I was absent 2 weeks. I try in the Options of statistics to use DropdownListBox Multi checed list in Jquery 
I try using the function : 
$("#page_analyze_param").dropdownchecklist();
for autorize multiple param selection but it seems not work in HG UI.
Have you some samples ?

**Pull request closed without merging**
