### PR TITLE
Zwave rework

### PR DESCRIPTION
**Pull request by Bounz**
Fixes to .csproj and CRC16Encap command class. Handlers folder renamed to CommandClasses.

### CODE REVIEW

**Comment by Bounz** [comment]
Wrong branch.

**Comment by genielabs** [comment]
Hey @hybridview ,

can you help testing current zwave-rework branch?

Thanks,
g.

**Comment by hybridview** [comment]
Sure thing. Could you tell me what the patch 1 and patch 2 folders are for? Just curious.

**Comment by genielabs** [comment]
These should be deleted, just small fixes I've made in place to Bounz code.

**Comment by hybridview** [comment]
I have tested the new code and everything appears to be working great so far. I had some exceptions at first during startup, but it was related to outdated MIG interface configs in my systemconfig file. After fixing that, no exceptions appear in the console.
My testing was mostly focused on automated multi-channel encapped reports (aka multi-instance v2) from my HEMv1 device.

**Comment by genielabs** [comment]
thansk @hybridview, I'm also testing since a couple of days and everything seems ok. I think I'm gonna merge this into master soon.

**Pull request closed without merging**
