### PR TITLE
Improvment of deleting wrong very high statistics value

### PR DESCRIPTION
**Pull request by dmayard**

### CODE REVIEW

**Comment by genielabs** [comment]
Hi @dmayard  I'm experiencing same issue sometimes.... do you know if is it due to bad Z-Wave communication? If so, I wonder why is the checksum valid for those bad values.

**Comment by dmayard** [comment]
I think perhaps it's due to bad ZWave communication. But in that case why the checksum would be ok ?
I look at some logs already, and in the case of error, the message is different. In my case it's principaly with AEONLabs HEM V2. Meter and KilowattHour messages have 2 parts of values, I analyze that it's the precedent value and the new one, in that case the value is always good. But with the error messages, the new value is specified and the precedent value is zero. I can send you some samples.

Cheers
Dani

**Comment by genielabs** [comment]
just trying to figure out if there's a way to discard those bad messages.

**Comment by dmayard** [comment]
It is easy to discard messages with very high value. But in that case  232 Kw is not a very high value.

**Comment by dmayard** [comment]
And some Sensor with Humidity for exemple on one that doesn't have these capability.

**Comment by genielabs** [comment]
Well, let's leave it as is for now. Discarding bigger values is something I've already tried, but as you said it's not a reliable approach.

**Pull request merged**
