### PR TITLE
Sync

### PR DESCRIPTION
**Pull request by ocalvo**
Suspend insteon listener thread while performing device discovery to avoid closing the COM port if an exception occurs.

### CODE REVIEW

**Comment by genielabs** [comment]
Hi ocalvo,
this is not compiling with mono. It complains about different target framework. Since I am concerned about changing all projects to target 4.5, we've got to find a 4.0 compatible solution. Let me know your thoughts about that.

**Comment by genielabs** [comment]
Changing HomeGenie project to target 4.5 it compiles without any error. Let's try this way.  I will merge this later.

**Comment by genielabs** [comment]
hi @ocalvo , I ended up trying a "soft" solution that does not require targeting changes.
Can you please verify that it is working this way too?

**Comment by ocalvo** [comment]
I don't think so. I will cook another fix that does not require targeting changes.

We really need a way to resume/suspend the thread and abort is just not an option.

Sent from my Windows Phone
________________________________

**Comment by genielabs** [comment]
ok @ocalvo , the best is that you do it because you can test it =) thanks!

**Comment by genielabs** [comment]
is this working now from last HG source code?

**Comment by ocalvo** [comment]
Hi, I had no time to test the last version. I think it will not because we really need to stop the thread during discovery.
I am in the process of moving to a brand new home, that's why I have not had any time to test the new code.(On the plus side, now I will be able to complete my dream of a fully automated home :) )
Sorry about the delay,
Thanks and regards,
Oscar CalvoDate: Wed, 15 Apr 2015 10:16:45 -0700

**Comment by genielabs** [comment]
@ocalvo , hg is now targetting 4.5.

**Pull request closed without merging**
