### PR TITLE
Added feature to invert GPIO 

### PR DESCRIPTION
**Pull request by gitbjo**
I have to control an 8 Relay Module, but the relay switches to On with a GPIO pin to LOW. The Raspberry Pi GPIO Library supports that, so I made use of it.
The Automation can now have an additional syntax !OUT, meaning we want a LOW when On.
I hope you agree to take it over in your repository.
Thanks,
gitbjo.

### CODE REVIEW

**Comment by genielabs** [comment]
this code will affect "pullup" "pulldown" resistor modes that is done by adding a "+" or "-" to the end of a OUT/IN value.
Did you try configuring as "OUT-" instead of just "OUT" (or "OUT+" not sure which one to use in your case)?

**Comment by gitbjo** [comment]
Hi Gene,

As per the code and the description, pull-up and pull-down are only used by IN doing IN+ and IN-.
For OUT there was nothing, so for sake of clarity, I used the "!OUT" to say NOT OUT (inverted logic).
so any IN+ and IN- should not be affected by this change.
I tested it with my relay board and it works perfectly as expected. Challenge testing is also done, as after the change, compile & run, to "OUT" config was still active and my relay were switched on. When I changed the config to "!OUT", my relays switched to off, when the switch was off. Switching on and off works now as expected.
Best Regards,
gitbjo

**Comment by genielabs** [comment]
Right I got confused sorry with IN/OUT =)
I will manually add your code since including/replacing a program in HG involves few steps as copying the generated dll as well and replace the new files in the homegenie_factory_config.zip as wel.

**Comment by genielabs** [comment]
@gitbjo I was going to add your code but I don't see where is the Reversed field used to invert the Status.Level logic. Shouldn't the *pinChanged* and the *WebService Control.On/Off*  use it?

**Comment by gitbjo** [comment]
Hi,
It is done through the GPIO library, no need to have application logic doing this.
Configured in line 3127:
`((OutputPinConfiguration)configuration[p]).Reversed = pc.Reversed;`
Is the setting as documented here: [PinConfiguration/Revert](https://github.com/raspberry-sharp/raspberry-sharp-io/wiki/Raspberry.IO.GeneralPurpose.PinConfiguration#revert)
Best Regards,
gitbjo

**Comment by genielabs** [comment]
ok, thanks for clarification. Next commit/update will contain this improvement.
Cheers,
g.

**Pull request closed without merging**
