### PR TITLE
Update thermostat.js

### PR DESCRIPTION
**Pull request by mtanana**
Fixed some Fahrenheit issues on the thermostat.  (Someone using Celsius might want to check this one out)

### CODE REVIEW

**Comment by mtanana** [comment]
Actually-  don't accept this yet.  I think the module has changed since the release I was working on.

**Comment by mtanana** [comment]
ok-  Checked and it should be fine with the newer release

**Comment by mtanana** [comment]
I'm also working on fixing a bug in the status change for some thermostat messages.  There is a cast class exception for the byte -> enum in the ZWave MIG.  I think I have it figured out....

**Comment by genielabs** [comment]
please if you're willing to work on ZWaveLib use the new repository as HG will be updated soon to use the new library.
https://github.com/genielabs/zwave-lib-dotnet
Much more easy to debug and work on zwave from its own project :)
I will wait some more before merging this, in case you've got some updates.

**Comment by mtanana** [comment]
Ohh-  didn’t see that you were revamping.  Yeah-  you can kick out this request and I’ll check out the new repository and put in a request there after I make sure it is compliant with the newer stuff.

**Pull request closed without merging**
